# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexacrm.github.io" # the base hostname & protocol for your site
twitter_username: alex4crm
github_username:  alexacrm

repository: AlexaCRM/alexacrm.github.io

# Build settings
markdown: kramdown
theme: minima

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: "wpcrm"
      type: "pages"
    values:
      layout: documentation
      group: wpcrm
      navigation: wpcrm
      jumbo_title: "Integration for Dynamics CRM"
      jumbo_lead: "A WordPress plugin that brings in the world of Microsoft Dynamics CRM."
  - scope:
      path: "toolkit"
      type: "pages"
    values:
      layout: documentation
      group: toolkit
      navigation: toolkit
      jumbo_title: "PHP CRM Toolkit"
      jumbo_lead: "Integration with Microsoft Dynamics CRM in PHP applications."
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:path/:basename/

navigation:
  wpcrm:
    Introduction: "/wpcrm/"
    Installation: "/wpcrm/installation/"
    Configuration: "/wpcrm/configuration/"
  toolkit:
    Introduction: "/toolkit/"
